apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: s3perf-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: origin
      description: The origin to download test artifacts from
      default: 'https://indy-gateway.psi.redhat.com'
      type: string
    - name: target
      description: The target storage service to test
      default: 'http://pathmap-storage-service.indy--runtime-int.svc.cluster.local'
      type: string
  tasks:
    - name: init
      taskRef:
        name: s3perf-init
      workspaces:
        - name: shared
          workspace: shared-workspace
    - name: execute
      taskRef:
        name: s3perf-execute
      params:
        - name: origin
          value: $(params.origin)
        - name: target
          value: $(params.target)
      runAfter:
        - init
      workspaces:
        - name: shared
          workspace: shared-workspace
