apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: s3perf-init
spec:
  params:
    - name: imageUrl
      description: The image to run the task
      default: 'quay.io/factory2/spmm-pipeline-base:latest'
      type: string
  steps:
    - name: git-clone
      image: $(params.imageUrl)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          git --version
          if [ ! -d "s3perf" ]; then
            git clone https://github.com/ruhan1/s3perf.git
          else
            cd s3perf
            git config --global --add safe.directory /workspace/s3perf
            git pull origin main
            git rev-parse HEAD
          fi
      workingDir: /workspace
  workspaces:
    - mountPath: /workspace
      name: shared
