apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: s3perf-prepare
spec:
  params:
    - name: imageUrl
      description: The image to run the task
      default: 'quay.io/factory2/spmm-pipeline-base:latest'
      type: string
    - name: origin
      description: The origin indy to download artifact from
      default: 'https://indy-gateway.psi.redhat.com'
      type: string
  steps:
    - name: init
      image: $(params.imageUrl)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          declare -a arr=(
            "foo/bar/1.0/bar-1.0.pom" 
            "foo/bar/1.0/bar-1.0.jar"
          )
          for i in "${arr[@]}"
          do
             echo "[download] $(params.imageUrl)/api/content/maven/hosted/repo-1/$i"
          done
          git --version
          git clone https://github.com/ruhan1/s3perf.git
      workingDir: /workspace
  workspaces:
    - mountPath: /workspace
      name: shared
